# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target '多环境变量demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking'
  # Pods for 多环境变量demo

end
